import type { Locale } from "./types"

export const copy = {
  zh: { overview: "总览", traders: "交易者", credentials: "交易凭证", linkit: "Linkit 通知", admin: "管理后台", createTrader: "新建交易者", createCredential: "新建凭证", noTraders: "还没有交易者", noCredentials: "还没有交易凭证", setup: "设为 Root 管理员", refresh: "刷新", enabled: "运行中", stopped: "已停止", failed: "失败", token: "信号 API Key", credential: "凭证", template: "策略模板", signal: "目标信号", params: "执行参数", runs: "最近运行", save: "保存", saving: "保存中…", rotating: "轮换中…", cancel: "取消", delete: "删除", language: "语言", root: "Root", owner: "用户", status: "状态", execution: "执行", enableTrader: "启动交易者", disableTrader: "停止交易者", traderEnabled: "交易者已启动", traderStopped: "交易者已停止", updated: "更新于", detail: "运行详情", linkitDescription: "保存 Linkit Bot 的 sk- Token 后，交易执行失败会向你的 Linkit 用户名发送私信。", configured: "已配置", notConfigured: "未配置", signin: "正在验证登录状态…", usage: "外部信号使用以下密钥调用 PATCH /signal/v1/traders/{trader_id}，请求体为 { signal: {...} }。完整密钥只显示一次。", manualSignal: "手动修改目标信号", manualSignalDescription: "保存前会按当前策略模板校验。保存仅更新目标信号，不会改变执行参数、交易凭证或运行开关。", signalPayload: "目标信号 JSON", manualSignalRiskTitle: "运行中交易者会使用新信号", manualSignalRisk: "此交易者正在运行；保存后，下一个执行周期可能按新的目标信号提交订单。保存本身不直接提交订单，也不会启动已停止的交易者。", signalSaved: "目标信号已保存", signalJsonInvalid: "目标信号 JSON 格式无效", signalJsonObject: "目标信号必须是 JSON 对象", tokenRotated: "信号 API Key 已轮换并复制", successfulRuns: "成功执行循环", signalHistory: "信号变更历史", signalHistoryDescription: "仅记录目标信号 PATCH 请求；相同 payload 会合并并累计出现次数。", occurrences: "出现次数", firstSeen: "首次出现" },
  en: { overview: "Overview", traders: "Traders", credentials: "Trading credentials", linkit: "Linkit notifications", admin: "Admin", createTrader: "Create trader", createCredential: "Create credential", noTraders: "No traders yet", noCredentials: "No trading credentials yet", setup: "Become root administrator", refresh: "Refresh", enabled: "Running", stopped: "Stopped", failed: "Failed", token: "Signal API key", credential: "Credential", template: "Strategy template", signal: "Target signal", params: "Execution parameters", runs: "Recent runs", save: "Save", saving: "Saving…", rotating: "Rotating…", cancel: "Cancel", delete: "Delete", language: "Language", root: "Root", owner: "User", status: "Status", execution: "Execution", enableTrader: "Start trader", disableTrader: "Stop trader", traderEnabled: "Trader started", traderStopped: "Trader stopped", updated: "Updated", detail: "Runtime details", linkitDescription: "Save a Linkit Bot sk- token to receive direct messages when one of your trader executions fails.", configured: "Configured", notConfigured: "Not configured", signin: "Checking your sign-in state…", usage: "External signals call PATCH /signal/v1/traders/{trader_id} with { signal: {...} }. The full key is shown once.", manualSignal: "Manually edit target signal", manualSignalDescription: "The current strategy template validates this before saving. Saving changes only the target signal, not execution parameters, credentials, or the run switch.", signalPayload: "Target signal JSON", manualSignalRiskTitle: "A running trader will use the new signal", manualSignalRisk: "This trader is running. Its next execution cycle may submit orders for the saved target signal. Saving does not submit an order directly or start a stopped trader.", signalSaved: "Target signal saved", signalJsonInvalid: "Target signal JSON is invalid", signalJsonObject: "Target signal must be a JSON object", tokenRotated: "Signal API key rotated and copied", successfulRuns: "Successful execution cycles", signalHistory: "Signal history", signalHistoryDescription: "Only target-signal PATCH requests are recorded. Identical payloads are coalesced and counted.", occurrences: "Occurrences", firstSeen: "First seen" },
} as const

export type Copy = Record<keyof typeof copy.zh, string>

export function localeText(t: Copy, english: string, chinese: string) {
  return t.overview === "总览" ? chinese : english
}

export function initialLocale(): Locale {
  return navigator.language.startsWith("zh") ? "zh" : "en"
}
